#ifndef FTNOIR_FILTER_BASE_GLOBAL_H
#define FTNOIR_FILTER_BASE_GLOBAL_H

#include <QtGlobal>

#ifdef FTNOIR_FILTER_BASE_LIB
# define FTNOIR_FILTER_BASE_EXPORT Q_DECL_EXPORT
#else
# define FTNOIR_FILTER_BASE_EXPORT Q_DECL_IMPORT
#endif

#endif // FTNOIR_FILTER_BASE_GLOBAL_H
