set(__depdir "${CMAKE_CURRENT_LIST_DIR}/../opentrack-depends")

function(setq name value)
    set("${name}" "${__depdir}/${value}" CACHE INTERNAL "" FORCE)
endfunction()

set(opentrack_install-debug-info TRUE CACHE INTERNAL "" FORCE)

setq(SDK_RIFT_140 "ovr_sdk_win_23.0.0/LibOVR")
setq(SDK_KINECT20 "nonfree/Kinect-v2.0")
setq(SDK_VJOYSTICK "vjoystick")
setq(SDK_PS3EYEDRIVER "PS3EYEDriver")
setq(SDK_REALSENSE "nonfree/RSSDK-R2")
setq(SDK_VALVE_STEAMVR "steamvr")
setq(SDK_FSUIPC "fsuipc")
setq(SDK_HYDRA "SixenseSDK")
setq(SDK_EYEWARE_BEAM "eyeware-beam-sdk")
setq(SDK_TOBII "nonfree/tobii-streamengine")

set(opentrack-use-onnxruntime-avx-dispatch 1)
if(CMAKE_SIZEOF_VOID_P GREATER 4)
    setq(Qt6_DIR "../qt-6.10.1-msvc/lib/cmake/Qt6")
    setq(OpenCV_DIR "opencv/build/msvc/install")
    setq(SDK_ARUCO_LIBPATH "aruco/build/msvc/src/aruco.lib")
    setq(SDK_LIBUSB "libusb-msvc")
    setq(SDK_GAMEINPUT "gameinput")
    setq(SDK_OSCPACK "oscpack/build/msvc")
    setq(ONNXRuntime_DIR "onnxruntime-win-x64-1.23.2")
endif()

if(CMAKE_GENERATOR STREQUAL "NMake Makefiles")
    set(CMAKE_MAKE_PROGRAM "jom" CACHE STRING "" FORCE)
endif()
