set(__depdir "${CMAKE_CURRENT_LIST_DIR}/../opentrack-depends")

function(setq name value)
    set("${name}" "${__depdir}/${value}" CACHE INTERNAL "" FORCE)
endfunction()

set(opentrack_install-debug-info TRUE CACHE INTERNAL "" FORCE)

setq(SDK_RIFT_140 "ovr_sdk_win_23.0.0/LibOVR")
setq(SDK_KINECT20 "nonfree/Kinect-v2.0")
setq(SDK_VJOYSTICK "vjoystick")
setq(SDK_PS3EYEDRIVER "PS3EYEDriver")
setq(SDK_REALSENSE "nonfree/RSSDK-R2")
setq(SDK_VALVE_STEAMVR "steamvr")
setq(SDK_FSUIPC "fsuipc")
setq(SDK_HYDRA "SixenseSDK")
setq(SDK_EYEWARE_BEAM "eyeware-beam-sdk")
setq(SDK_TOBII "nonfree/tobii-streamengine")
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    setq(Qt6_DIR "../qt-6.10.1-msvc-2022/lib/cmake/Qt6")
    setq(OpenCV_DIR "opencv/build/2022/install")
    setq(SDK_ARUCO_LIBPATH "aruco/build/2022/src/aruco.lib")
    setq(SDK_LIBUSB "libusb-2022")
    setq(SDK_GAMEINPUT "gameinput")
    setq(ONNXRuntime_DIR "onnxruntime-1.23.2-msvc-2022-avx")
    install(FILES "${__depdir}/onnxruntime-1.23.2-msvc-2022-noavx/bin/onnxruntime.dll" RENAME "onnxruntime-noavx.dll" DESTINATION "modules")
    install(FILES "${__depdir}/onnxruntime-1.23.2-msvc-2022-avx/bin/onnxruntime.dll" RENAME "onnxruntime-avx.dll" DESTINATION "modules")
    set(opentrack-use-onnxruntime-avx-dispatch 1)
    setq(SDK_OSCPACK "oscpack/build/2022")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    etq(Qt6_DIR "../qt-6.9.1-msvc-2022-x86/lib/cmake/Qt6")
    setq(OpenCV_DIR "opencv/build/2022-x86/install")
    setq(SDK_ARUCO_LIBPATH "aruco/build/2022-x86/src/aruco.lib")
    setq(SDK_LIBUSB "libusb-2022-x86")
    setq(ONNXRuntime_DIR "onnxruntime-1.23.2-msvc-2022-avx-x86")
    setq(SDK_OSCPACK "oscpack/build/2022-x86")
else()
    message(FATAL_ERROR "unknown word size ${CMAKE_SIZEOF_VOID_P}")
endif()

#set(CMAKE_ASM_NASM_COMPILER nasm.exe CACHE FILEPATH "" FORCE)

#set(qt6Core_DIR "${qt6_DIR}Core" CACHE PATH "" FORCE)
#set(qt6Gui_DIR "${qt6_DIR}Gui" CACHE PATH "" FORCE)

if(CMAKE_GENERATOR STREQUAL "NMake Makefiles")
    set(CMAKE_MAKE_PROGRAM "jom" CACHE STRING "" FORCE)
endif()
