#pragma once

#define ARUCOHEAD_MIN_VECTOR_SAMPLES 5
#define ARUCOHEAD_MAX_VECTOR_SAMPLES 20
#define ARUCOHEAD_LINE_THICKNESS_FRAME_SCALING_FACTOR (1.0/320.0)
#define ARUCOHEAD_MARKER_FLIP_DETECTION_THRESHOLD 120.0
#define ARUCOHEAD_MARKER_REPROJECTION_ERROR_THRESHOLD 0.2