#include <QWidget>
#include <QMessageBox>
#include <QProcess>
#include <QImage>
#include <QLabel>
#include <QCoreApplication>
#include <QIcon>
#include <QHBoxLayout>
#include <QTimer>
#include <QPainter>
#include <QPaintEvent>
#include <QList>
#include <QString>
