function(setq name value)
    set("${name}" "${value}" CACHE INTERNAL "" FORCE)
endfunction()

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT OR "${CMAKE_INSTALL_PREFIX}" STREQUAL "")
    setq(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install")
endif()

if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/opentrack-policy.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/opentrack-policy.cmake" NO_POLICY_SCOPE)
endif()

setq(CMAKE_BUILD_TYPE RELEASE)

# search for programs in the host directories
# don't poison with system compile-time data
setq(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER
     CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY
     CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

#add_compile_options(-Qvec-report:2)
#add_compile_options(-d2cgsummary)
add_definitions(-D_HAS_EXCEPTIONS=0)

if(DEFINED CMAKE_TOOLCHAIN_FILE)
    # ignore cmake warning: Manually-specified variable not used by the project
    setq(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/opentrack-policy.cmake" NO_POLICY_SCOPE)
setq(CMAKE_POLICY_DEFAULT_CMP0069 NEW)
setq(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)

setq(CMAKE_C_EXTENSIONS FALSE)
setq(CMAKE_CXX_EXTENSIONS FALSE)

function(add_c_cxx_options)
    add_compile_options($<$<OR:$<COMPILE_LANGUAGE:C>,$<COMPILE_LANGUAGE:CXX>>:${ARGV}>)
endfunction()

if(CMAKE_PROJECT_NAME STREQUAL "opentrack")
    #include("${CMAKE_CURRENT_LIST_DIR}/opentrack-policy.cmake" NO_POLICY_SCOPE)

    add_compile_options("-W4")

    # C4265: class has virtual functions, but destructor is not virtual
    # C4005: macro redefinition
    set(warns-error 4265 4005)

    foreach(i ${warns-error})
        add_compile_options(-w1${i} -we${i})
    endforeach()

elseif(CMAKE_PROJECT_NAME STREQUAL "OpenCV")
    setq(PARALLEL_ENABLE_PLUGINS                OFF)
    setq(HIGHGUI_ENABLE_PLUGINS                 OFF)
    setq(VIDEOIO_ENABLE_PLUGINS                 OFF)
    setq(ENABLE_FAST_MATH                       ON)
    setq(ENABLE_LTO                             ON)
    setq(BUILD_WITH_STATIC_CRT                  OFF)
    setq(ENABLE_PRECOMPILED_HEADERS             ON)
    setq(INSTALL_PDB_COMPONENT_EXCLUDE_FROM_ALL OFF)
    setq(CV_TRACE                               OFF)
    setq(OPENCV_DISABLE_THREAD_SUPPORT          ON)
    setq(OPENCV_SKIP_MSVC_EXCEPTIONS_FLAG       ON)
    setq(OPENCV_SKIP_MSVC_PARALLEL              ON)
    setq(BUILD_PACKAGE                          OFF)
    setq(BUILD_PERF_TESTS                       OFF)
    setq(BUILD_PROTOBUF                         OFF)
    setq(BUILD_TESTS                            OFF)
    setq(BUILD_opencv_apps                      OFF)
    setq(BUILD_opencv_dnn                       OFF)
    setq(BUILD_opencv_gapi                      OFF)
    setq(BUILD_opencv_java_bindings_generator   OFF)
    setq(BUILD_opencv_js                        OFF)
    setq(BUILD_opencv_js_bindings_generator     OFF)
    setq(BUILD_opencv_ml                        OFF)
    setq(BUILD_opencv_objc_bindings_generator   OFF)
    setq(BUILD_opencv_photo                     OFF)
    setq(BUILD_opencv_python_bindings_generator OFF)
    setq(BUILD_opencv_python_tests              OFF)
    setq(BUILD_opencv_stitching                 OFF)
    setq(BUILD_opencv_ts                        OFF)
    setq(ccitt                                  OFF)
    setq(logluv                                 OFF)
    setq(lzw                                    OFF)
    setq(mdi                                    OFF)
    setq(next                                   OFF)
    setq(packbits                               OFF)
    setq(thunder                                OFF)
    setq(BUILD_JASPER                           OFF)
    setq(BUILD_JPEG                             OFF)
    setq(BUILD_OPENEXR                          OFF)
    setq(BUILD_OPENJPEG                         OFF)
    setq(BUILD_PNG                              OFF)
    setq(BUILD_TIFF                             OFF)
    setq(BUILD_WEBP                             OFF)
    setq(BUILD_ZLIB                             OFF)
    setq(WITH_ADE                               OFF)
    setq(WITH_ARITH_DEC                         OFF)
    setq(WITH_ARITH_ENC                         OFF)
    setq(WITH_AVIF                              OFF)
    setq(WITH_DIRECTML                          OFF)
    setq(WITH_DIRECTX                           OFF)
    setq(WITH_EIGEN                             OFF)
    setq(WITH_FFMPEG                            OFF)
    setq(WITH_FLATBUFFERS                       OFF)
    setq(WITH_IMGCODEC_GIF                      OFF)
    setq(WITH_IMGCODEC_HDR                      OFF)
    setq(WITH_IMGCODEC_PFM                      OFF)
    setq(WITH_IMGCODEC_PXM                      OFF)
    setq(WITH_IMGCODEC_SUNRASTER                OFF)
    setq(WITH_JASPER                            OFF)
    setq(WITH_JPEG                              OFF)
    setq(WITH_JPEGXL                            OFF)
    setq(WITH_LAPACK                            OFF)
    setq(WITH_MSMF                              OFF)
    setq(WITH_MSMF_DXVA                         OFF)
    setq(WITH_OBSENSOR                          OFF)
    setq(WITH_OPENCLAMDBLAS                     OFF)
    setq(WITH_OPENCLAMDFFT                      OFF)
    setq(WITH_D3D11_NV                          OFF)
    setq(WITH_OPENEXR                           OFF)
    setq(WIIH_OPENJPEG                          OFF)
    setq(WITH_PNG                               OFF)
    setq(WITH_TIFF                              OFF)
    setq(WITH_VTK                               OFF)
    setq(WITH_WEBP                              OFF)
    add_compile_options(-wd4530)
    set(OPENCV_PYTHON_SKIP_DETECTION 1)

elseif(CMAKE_PROJECT_NAME STREQUAL "TestOscpack")
    add_compile_definitions(OSC_HOST_LITTLE_ENDIAN)

elseif(PROJECT_NAME STREQUAL "onnxruntime")
    setq(onnxruntime_BUILD_SHARED_LIB           ON)
    setq(BUILD_SHARED_LIBS                      OFF)
    setq(ONNX_USE_MSVC_STATIC_RUNTIME           OFF)
    setq(protobuf_MSVC_STATIC_RUNTIME           OFF)
    setq(protobuf_MSVC_STATIC_RUNTIME           OFF)
    setq(ABSL_MSVC_STATIC_RUNTIME               OFF)
    setq(BUILD_TESTING                          OFF)
    setq(onnxruntime_BUILD_BENCHMARKS           OFF)
    setq(onnxruntime_BUILD_FOR_NATIVE_MACHINE   OFF)
    setq(onnxruntime_BUILD_UNIT_TESTS           OFF)
    setq(protobuf_BUILD_EXAMPLES                OFF)
    setq(protobuf_BUILD_SHARED_LIBS             OFF)
    setq(ONNX_BUILD_BENCHMARKS                  OFF)
    setq(ONNX_BUILD_TESTS                       OFF)
    setq(ONNX_DISABLE_EXCEPTIONS                OFF)
    setq(ONNX_GEN_PB_TYPE_STUBS                 OFF)
    setq(onnxruntime_DISABLE_CONTRIB_OPS        ON)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    add_c_cxx_options(-sdl- -GS- -wd4100 -wd4709 -wd4244 -wd4267 -wd4996)
    add_compile_options($<$<COMPILE_LANGUAGE:ASM_MASM>:-nologo>)
    add_definitions(-DNDEBUG)

elseif(PROJECT_NAME STREQUAL "Qt")
    if(NOT LLVM_DIR AND NOT LLVM_INSTALL_DIR)
        setq(QT_BUILD_SUBMODULES "qtbase;qtserialport;qttools")
        setq(QT_BUILD_DOCS                      OFF)
        setq(BUILD_qtactiveqt                   OFF)
        setq(BUILD_qtdeclarative                OFF)
        setq(BUILD_qtimageformats               OFF)
        setq(BUILD_qtlanguageserver             OFF)
        setq(BUILD_qtshadertools                OFF)
        setq(BUILD_qtsvg                        OFF)
        setq(FEATURE_qdoc                       OFF)
    endif()
    setq(FEATURE_linguist                       ON)
    setq(FEATURE_qdoc                           OFF)
    setq(FEATURE_debug_and_release              OFF)
    setq(FEATURE_force_debug_info               ON)
    setq(FEATURE_shared                         ON)
    add_definitions(-DNDEBUG)
endif()

setq(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
add_c_cxx_options(-MD)

setq(_CFLAGS                    "-diagnostics:caret -Zc:inline -Zc:static_assert- -wd4117 -Zi -Zf -Zo -bigobj -vd0")
setq(_CFLAGS_RELEASE            "-O2 -Oit -Oy- -Ob3 -fp:fast -GS- -GF -GL -Gw -Gy")
setq(_CFLAGS_DEBUG              "-guard:cf -MTd -Gs0 -RTCs")
setq(_CXXFLAGS                  "${_CFLAGS} -Zc:throwingNew -Zc:lambda")
setq(_CXXFLAGS_RELEASE          "${_CFLAGS_RELEASE}")
setq(_CXXFLAGS_DEBUG            "${_CFLAGS_DEBUG}")
setq(_LDFLAGS                   "-INCREMENTAL:NO")
setq(_LDFLAGS_RELEASE           "-OPT:REF,ICF=10 -DEBUG:FULL")
setq(_LDFLAGS_DEBUG             "-DEBUG:FULL")
setq(_LDFLAGS_STATIC            "")
setq(_LDFLAGS_STATIC_RELEASE    "-LTCG")
setq(_LDFLAGS_STATIC_DEBUG      "")

string(TOUPPER "${CMAKE_BUILD_TYPE}" upcase_CMAKE_BUILD_TYPE)

foreach(k "" "_${upcase_CMAKE_BUILD_TYPE}")
    set("FLAGS_CXX${k}"     "" CACHE STRING "More CMAKE_CXX_FLAGS${k}")
    set("FLAGS_C${k}"       "" CACHE STRING "More CMAKE_C_FLAGS${k} (almost never used)")
    set("FLAGS_LD${k}"      "" CACHE STRING "More CMAKE_(SHARED|EXE|MODULE)_LINKER_FLAGS${k}")
    set("FLAGS_ARCHIVE${k}" "" CACHE STRING "More CMAKE_STATIC_LINKER_FLAGS${k}")
endforeach()

foreach(k "" "_${CMAKE_BUILD_TYPE}")
    #set(CMAKE_STATIC_LINKER_FLAGS${k} "${CMAKE_STATIC_LINKER_FLAGS${k}} ${_LDFLAGS_STATIC${k}}")
    set(CMAKE_STATIC_LINKER_FLAGS${k} "${_LDFLAGS_STATIC${k}} ${FLAGS_ARCHIVE${k}}" CACHE STRING "" FORCE)
endforeach()
foreach(j "" "_${CMAKE_BUILD_TYPE}")
    foreach(i MODULE EXE SHARED)
        #set(CMAKE_${i}_LINKER_FLAGS${j} "${CMAKE_${i}_LINKER_FLAGS${j}} ${_LDFLAGS${j}}")
        set(CMAKE_${i}_LINKER_FLAGS${j} "${_LDFLAGS${j}} ${FLAGS_LD${j}}" CACHE STRING "" FORCE)
    endforeach()
endforeach()

foreach(j C CXX)
    foreach(i "" "_${CMAKE_BUILD_TYPE}")
        #set(CMAKE_${j}_FLAGS${i} "${CMAKE_${j}_FLAGS${i}} ${_${j}FLAGS${i}}")
        set(CMAKE_${j}_FLAGS${i} "${_${j}FLAGS${i}} ${FLAGS_${j}${i}}" CACHE STRING "" FORCE)
    endforeach()
endforeach()
