macro(opentrack_rift_boilerplate proj opt)
    if(${opt})
        set(link-flags)
        set(c-flags)
        if(APPLE)
            set(link-flags "-framework CoreFoundation -framework CoreGraphics -framework IOKit -framework Quartz")
            set(c-flags "-fno-strict-aliasing")
        else()
            if(NOT MSVC)
                    set(c-flags "-fno-strict-aliasing")
            endif()
        endif()
        opentrack_boilerplate("${proj}" LINK ${link-flags} COMPILE ${c-flags})
        set(proj ${opentrack-project-name})
        target_include_directories(${proj} SYSTEM PUBLIC ${${opt}}/Include ${${opt}}/Src)
        set(c-flags)
        set(link-flags)
        if(WIN32)
            if(MSVC)
                set(ext lib)
                set(p)
            else()
                set(ext a)
                set(p lib)
            endif()
            target_link_libraries(${proj} ${${opt}}/${p}LibOVR.${ext} winmm setupapi ws2_32 imagehlp wbemuuid)
            set(ext)
            set(p)
        else()
            if(NOT APPLE)
                target_link_libraries(${proj} ${${opt}}/libLibOVR.a udev Xinerama)
            else()
                target_link_libraries(${proj} ${${opt}}/libLibOVR.a)
            endif()
        endif()
    endif()
endmacro()
