include(CheckTypeSize)
check_type_size(void* opentrack-word-size BUILTIN_TYPES_ONLY LANGUAGE C)
if(NOT ((opentrack-word-size EQUAL 4) OR (opentrack-word-size EQUAL 8)))
    message(FATAL_ERROR "word size '${opentrack-word-size}' either misdetected or really not 4 or 8")
endif()
set(opentrack-word-size ${opentrack-word-size})
if(opentrack-word-size GREATER 4)
    set(opentrack-64bit TRUE)
else()
    set(opentrack-64bit FALSE)
endif()
