if(WIN32 OR APPLE OR CYGWIN)
    set(opentrack-hier-pfx ".")
    set(opentrack-hier-path "/./")
    set(opentrack-hier-doc ".")
    set(opentrack-hier-str RUNTIME DESTINATION . LIBRARY DESTINATION .)
else()
    set(opentrack-hier-pfx "libexec/opentrack")
    set(opentrack-hier-path "/../libexec/opentrack/")
    set(opentrack-hier-doc "share/doc/opentrack")
    set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${opentrack-hier-pfx}")
    set(opentrack-hier-str ARCHIVE DESTINATION lib/opentrack LIBRARY DESTINATION ${opentrack-hier-pfx} RUNTIME DESTINATION bin)
endif()

set(opentrack-binary-suffix "")
if(APPLE)
    set(opentrack-binary-suffix ".bin")
elseif(WIN32)
    set(opentrack-binary-suffix ".exe")
endif()
