if(NOT opentrack-rift-included)
    set(opentrack-rift-included TRUE)
    function(opentrack_rift_boilerplate proj opt)
        if(${opt})
            set(link-flags)
            set(c-flags)
            if(APPLE)
                set(link-flags "-framework CoreFoundation -framework CoreGraphics -framework IOKit -framework Quartz")
                set(c-flags "-fno-strict-aliasing")
            elseif(NOT MSVC)
                set(c-flags "-fno-strict-aliasing")
            endif()
            opentrack_boilerplate(${proj} LINK ${link-flags} COMPILE ${c-flags})
            set(proj ${proj})
            target_include_directories(${proj} SYSTEM PUBLIC ${${opt}}/Include ${${opt}}/Src)
            set(c-flags)
            set(link-flags)
            if(MSVC)
                set(ext lib)
                set(p)
            else()
                set(ext a)
                set(p lib)
            endif()
            if(MSVC)
                set(pfx "")
            else()
                set(pfx "lib")
            endif()
            target_link_libraries(${proj} ${${opt}}/${pfx}LibOVR.${ext})
            if(WIN32)
                target_link_libraries(${proj} winmm setupapi ws2_32 imagehlp wbemuuid)
                set(ext)
                set(p)
            elseif(NOT APPLE)
                target_link_libraries(${proj} udev Xinerama)
            endif()
        endif()
    endfunction()
endif()
