include(CheckTypeSize)
check_type_size(void* opentrack-word-size BUILTIN_TYPES_ONLY LANGUAGE C)
if(opentrack-word-size LESS 4)
    message(FATAL_ERROR "word size '${opentrack-word-size}' either misdetected or really less than 4")
endif()
set(opentrack-word-size ${opentrack-word-size})
if(opentrack-word-size EQUAL 8)
    set(opentrack-64bit TRUE)
else()
    set(opentrack-64bit FALSE)
endif()
