#pragma once

//#define UI_FORCED_TRACKER "pt"
//#define UI_FORCED_FILTER "accela"

//#define UI_NO_TRACKER_COMBOBOX
//#define UI_NO_FILTER_COMBOBOX

//#define UI_NO_TRACKER_SETTINGS_BUTTON
//#define UI_NO_FILTER_SETTINGS_BUTTON

//#define UI_NO_RAW_DATA
//#define UI_NO_GAME_DATA
//define UI_ACCELA_OLD_STAIRCASE
